[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "focused_window"
format = "| $title.str(0,21)"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play|}"
[[block.click]] # scroll to update the volume
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]] # use next&prev to change the current song
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon $utilization $temperature $clocks "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "notify"
