theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
max_width = 50
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"
dynamic_width = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "sound"
on_click = "pactl set-sink-mute 0 toggle"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "notify"
