theme = "monokai_without_background"

[editor]
scrolloff = 999
auto-pairs = false
mouse = false
cursorline = true
gutters = ["diagnostics",  "diff"]
true-color = true
popup-border = "all"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
"'" = "insert_mode"
"\\" = "undo"
"|" = "redo"

# Movements:
# Single move:
r = "move_char_left" # Maps the 'a' key to the move_char_left command
t = "move_line_down" # Maps the 'w' key move_line_up
i = "move_line_up" # Maps the 'w' key move_line_up
u = "move_char_right" # Maps the 'a' key to the move_char_left command
# Word move:
b = "move_prev_word_start"
"B" = "move_prev_long_word_start"
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"

# Find
# j = "find_till_char"
# J = "till_prev_char"
# h = "replace" # Maps the 'a' key to the move_char_left command
# H = "replace_with_yanked" # Maps the 'a' key to the move_char_left command

# l = "search_next"
# A-l = "extend_search_next"
# L = "search_prev"
# A-L = "extend_search_prev"

S = "select_regex"
"A-S" = "split_selection"

"À" = ":toggle lsp.display-inlay-hints"
"Y" = ":set gutters [\"diagnostics\",\"line-numbers\",\"diff\"]"
"X" = ":set gutters [\"diagnostics\",\"diff\"]"

[keys.select]
r = "extend_char_left"
t = "extend_line_down"
i = "extend_line_up"
u = "extend_char_right"

j = "extend_till_char"
J = "extend_till_prev_char"
f = "extend_next_char"
F = "extend_prev_char"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode

# [keys.view]
# t = "align_view_top"
# s = "scroll_down"
# r = "scroll_up"

[editor.indent-guides]
render = true
character = "│"
